// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg-V4K_YPuxlEpeLXQsP7mdAmoEg8ic0M',
    appId: '1:157893563171:web:15c0dccdee3d600e52b296',
    messagingSenderId: '157893563171',
    projectId: 'idfood-ac307',
    authDomain: 'idfood-ac307.firebaseapp.com',
    storageBucket: 'idfood-ac307.appspot.com',
    measurementId: 'G-893BHW5K7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Sn7DtU3CLVIIC1hO-W4HLOcuTmQX6Sw',
    appId: '1:157893563171:android:73f91fa0a376296952b296',
    messagingSenderId: '157893563171',
    projectId: 'idfood-ac307',
    storageBucket: 'idfood-ac307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlZySQtQQn7da6sHHFyXyn9M_j9fE9Lw',
    appId: '1:157893563171:ios:49d7e0588f8a644c52b296',
    messagingSenderId: '157893563171',
    projectId: 'idfood-ac307',
    storageBucket: 'idfood-ac307.appspot.com',
    iosClientId: '157893563171-jknuotmhhon0v7seacohd696rb5e581v.apps.googleusercontent.com',
    iosBundleId: 'com.dhyass.idfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAlZySQtQQn7da6sHHFyXyn9M_j9fE9Lw',
    appId: '1:157893563171:ios:49d7e0588f8a644c52b296',
    messagingSenderId: '157893563171',
    projectId: 'idfood-ac307',
    storageBucket: 'idfood-ac307.appspot.com',
    iosClientId: '157893563171-jknuotmhhon0v7seacohd696rb5e581v.apps.googleusercontent.com',
    iosBundleId: 'com.dhyass.idfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg-V4K_YPuxlEpeLXQsP7mdAmoEg8ic0M',
    appId: '1:157893563171:web:64120d048f4e86fe52b296',
    messagingSenderId: '157893563171',
    projectId: 'idfood-ac307',
    authDomain: 'idfood-ac307.firebaseapp.com',
    storageBucket: 'idfood-ac307.appspot.com',
    measurementId: 'G-N4RQWH6SZ1',
  );
}
